### ISSUE TITLE
Certain posts aren't showing up on the Group map

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1028]
Posts from members in the Holochain Advocates Community aren't showing up on the Group Map. Certain members have posted events and offers, though only members are displaying.

![HACC map - no three lines](https://user-images.githubusercontent.com/92816219/147709140-03671c81-7ec6-414d-bac3-148413f44680.jpg)

**Comment by tibetsprague** [comment]
looking through all the posts in the group i dont see any ones with locations, can you double check with Anita @KrishaTerranIO ?

**Comment by tibetsprague** [comment]
after talking to anita it seems this is not actually broken
