### ISSUE TITLE
Text Formatting in Posts: Whitespace formatting is not functioning properly.

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1029]
Inability to create paragraphs, spaces between lines of text and have them display when the post is saved. It appears correct while editing, but when saved, default to a stream of lines regardless if there was a block of space created while editing or if several blank lines were intended in the text. 

See images:
<img width="282" alt="text formatting problem" src="https://user-images.githubusercontent.com/92816219/147961963-804e586a-94b4-40ae-b1c9-880636bb25c8.PNG">

**Comment by lorenjohnson** [comment]
☝🏼Note: If what goes to the backend changes, or the formatting choices on the front end change make sure to sync on whether this works and displays consistently on mobile.
