### ISSUE TITLE
Click on map to create a post

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1046]
See Aaron's design below. Clicking on the Cursor changes to a plus icon. 
Clicking on map pops up create dialog with new title. 
We will also pass the lat,lng of the location to the create dialog which will appear in the location field for the new post. 
(Let's write a click to get coordinate from the map general function.)

The create dialog's title should change to "What would you like to create at this location?"
Remove discussion from the list in the create dialog for now since it does not have a location.

After the post or group is created it should appear on the map immediately. 

* depending on how this is implemented this could require changes in mobile app to work, make sure it doesnt break the mobile app *

**Comment by brodeur** [comment]
https://www.figma.com/file/aBZ1d4hg1gMW0MR7NhZoqs/Add-posts-to-map?node-id=0%3A1

**Comment by lorenjohnson** [comment]
@Sofacosta has completed most of the work for this feature here: https://github.com/Hylozoic/hylo-evo/pull/1138

Currently though the new Post will not make it to the `queryResults` for the Map Explorer or Map Explorer Drawer as there is no `queryResults` reducer handling of the `FETCH_POSTS_MAP` or `FETCH_POSTS_MAP_DRAWER` actions. These likely / hopefully can be handled the same as they are with the `FETCH_POSTS` used on the feed, adding the additional types to `store/reducers/queryResults.js`. There also may be a case here to re-factor the `FETCH_POSTS_MAP...` queries into the existent `FETCH_POSTS` action.

**Comment by tibetsprague** [comment]
Some questions/issues:

- [ ] Right now the way sofia set it up is you just click and hold for a second on the map to add a post, she has not yet added the create post state button in your designs @brodeur . One thing is confusing in your designs though, it says “When map is pressed for 1 second without moving, dragging or scrolling, open post creation modal with the location pressed as the location of the post”, but doesn’t specify if this happens always, or only when the state button is pressed. I could see having both features, without the add post button pressed you can still click and hold for a second to create a post, but with the button pressed then another click instantly creates a post. Or Aaron did you mean that even after clicking the button you still have to click and hold for a second?
- [ ] after you create the post should it unselect the create post mode or stay in it?
- [ ] I'm seeing a bug where maybe 20% of the time the lat/lng comes up as a 0
- [ ] Another bug is that when you create a post it removes all the other query parameters from the URL so if you refresh the map it moves to a different viewport. Those params should be kept in the URL on the redirect to the post
- [ ] Also right now we are still showing the Discussion post type which doesn't currently have a location. We should either remove Discussion from the list, or just add location to Discussion! Which is not that much work at all. Decision being made here

**Comment by tibetsprague** [comment]
ticket to add posts immediately to the map https://github.com/Hylozoic/hylo-evo/issues/1143

**Comment by lorenjohnson** [comment]
Also, we forgot to keep this in PR until someone addresses the `queryResolver` stuff for map.

**Comment by tibetsprague** [comment]
fixed the queryResults stuff!
