### ISSUE TITLE
Show indigenous territories as layer on the map

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1048]
From [native-land.ca](https://www.figma.com/file/hITe76b9jN7BJuapxuUBuN/Rebirth?node-id=11%3A50)

We probably pull this data and cache locally once per day

“If you’re using this dataset for your project and you want to properly credit it, it’s not too hard. You can give credit to “Native Land Digital”, and link to our website. The dataset is publicly available and is not under any proprietary license; the work can be considered under a CC0 license (free to use in any way you like). We would, however, kindly ask that you consider the morality of how you use this dataset, be aware that it is constantly changing, and that it is not meant or reasonably to use for academic or legal purposes."

**Comment by thomasgwatson** [comment]
https://www.mapbox.com/mts

**Comment by tibetsprague** [comment]
add a link to native lands
