### ISSUE TITLE
Public landing page for public groups (based on GroupDetail)

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1050]
Should be able to go to the URL for a public group and view it without being signed in to Hylo. If the group is open or restricted you can request to join but then you have to sign in to Hylo first.

This displays the GroupDetail component, just like if a signed in user goes to a group URL they are not a member of yet

**Comment by thomasgwatson** [comment]
There is already some changes on the farm branch that are related to this, so this work ought to be branched from the farm branch.

**Comment by lorenjohnson** [comment]
> There is already some changes on the farm branch that are related to this, so this work ought to be branched from the farm branch.

I am likely missing something but, but is it ok to stall this until farm release (don't know the expected timing of that)? @thomasgwatson could this be merged and then you merge-up dev back into farm and resolve conflicts there?

**Comment by tibetsprague** [comment]
@brodeur we need a bit of design here, how does the header/footer/navigation of this page look? how does it integrate into the rest of the hylo.com website? you should be able to navigate away from the page somehow

**Comment by tibetsprague** [comment]
@thomasgwatson why did you close this one? i dont think its done

**Comment by thomasgwatson** [comment]
They are available eg: https://www.hylo.com/groups/heart-orchard

Or was this ticket specifically for non-logged in public views?

**Comment by tibetsprague** [comment]
Yes, non-logged in
