### ISSUE TITLE
Group explorer: Farm group type filtering

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1120]
Add filters by various fields in the farm schema to the group explorer when farm type is selected

**Comment by tibetsprague** [comment]
Which fields do we want to filter by @brodeur @thomasgwatson @cpolitano ?

**Comment by thomasgwatson** [comment]
Farm Filtering (on Group Explorer farms tab)
Farm Type Filter > core.types 
Region > sort by distance from me OR search input: location OR map
Management Practice > core.management_plans_current, core_certifications_current
Product_categories OR search: Product_details & Animal_types


UX
Return any farm that matches any of the filters, and sort by most matches
Nice to have: Allow multi-select, each filter condition shows up as a pill
-Nearest is default for farm search


Backend-notes:
Combined AND logic search, with OR logic search tacked to end of that.

**Comment by thomasgwatson** [comment]
![Group Explorer_ Filters open](https://user-images.githubusercontent.com/5193218/156662949-f1badf15-5e7c-4eff-b948-938714fdfb0d.png)
![Group Explorer_ Filters](https://user-images.githubusercontent.com/5193218/156662954-caf0f2c1-6678-49e8-871d-79fd51469f49.png)
