### ISSUE TITLE
Use customized group nouns in EVO

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo-evo#1122]
Use group type_descriptor to display instead of Group on the group about page. For now might want to be called "farm, ranch, temple, coven, organization, conspiracy" etc etc.

Use moderator_descriptor field instead of the word Moderator(s) in the UI. 

We need to figure out where the nouns need to be displayed and add conditional logic that deals with any pluralization needed. Or we may have separate plural fields in the database. Look for libraries that do this for us?

**Comment by tibetsprague** [comment]
@brodeur need designs for the Group Settings part of this

**Comment by tibetsprague** [comment]
Do we keep using the word moderator in situations like the Send Announcement modal which says Only Moderators can use this feature? We might have to because you could have selected to share to multiple groups and they might use different words.
