### ISSUE TITLE
Default topics not showing up when creating a post

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1133]
When creating a post in the Building Hylo group, I noticed that the default topics were not showing up when in the topics section. I double checked the group topics settings, and there were default topics set. 
<img width="741" alt="Screen Shot 2022-03-03 at 1 54 08 PM" src="https://user-images.githubusercontent.com/92816219/156659075-fa4cf3dd-8abd-4da7-8642-3df2938eae55.png">

**Comment by tibetsprague** [comment]
Dang, good catch
