### ISSUE TITLE
`At a glance` widget for farms

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1155]
Display the website, social media link and keywords for a farm

**Comment by tibetsprague** [comment]
Is this for all groups? or just farm groups? 
@brodeur i think the group purpose should maybe be here right at the top?

**Comment by thomasgwatson** [comment]
https://www.figma.com/file/ds9HkBxld0mBFfv1O3rihz/Group-Explorer?node-id=1485%3A2

**Comment by thomasgwatson** [comment]
@brodeur I think we need icons assets for both of these icons displayed here. The top one doesn't seem to exist, and while we do have an instagram icon asset, I think its better for now if we just have a generic 'social media' icon we can fall back on, and detect specific sites and match icons in the future

![image](https://user-images.githubusercontent.com/5193218/162053190-bed621a2-a16c-480b-b14a-ca39b84c9fea.png)
