### ISSUE TITLE
Show/edit purpose field for groups

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1157]
- [x] Add to create modal
- [x] Edit in settings
- [x] When viewing a group About page in the Group Explorer (ex url https://www.hylo.com/public/groups/group/2021phca) - Bold Purpose and the purpose below
- [x] Probably should have a character limit, what is it? 500
- [x] viewing the group About page as a person who is not a member of group / is not logged-in (ex url https://www.hylo.com/groups/bay-area-bioregion)
- [x] when a new member is joining the group, in the wizard where they select skills
- [x] on a group’s Explore page (ex url https://www.hylo.com/groups/bay-area-bioregion/explore)
- [x] on a group’s About page as a member of the group - About panel should expand from right (ex url https://www.hylo.com/groups/bay-area-bioregion)
- [x] In the main group Stream, as a member of the group, on the right-hand panel

**Comment by brodeur** [comment]
Designs here: https://www.figma.com/file/jUrR059lSbQaYt9rykcNMk/Group-Purpose?node-id=3%3A12

Character limit: 144
