### ISSUE TITLE
Add new options to farm collaborate widget

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1160]
Clare adding new options via Greg to the schema

Will need new icons for the new options

**Comment by thomasgwatson** [comment]
Full list now:

  {
    'value': 'research',
    'label': 'Research'
  },
  {
    'value': 'events',
    'label': 'Cohosting events'
  },
  {
    'value': 'volunteering',
    'label': 'Volunteering opportunities'
  },
  {
    'value': 'mentorship',
    'label': 'Offering mentorship & advice'
  },
  {
    'value': 'cooperative',
    'label': 'Cooperative and supply-chain development'
  },
  {
    'value': 'buy',
    'label': 'Buy our products'
  },
  {
    'value': 'markets',
    'label': 'Access to new markets'
  },
  {
    'value': 'ecosystem_service_markets',
    'label': 'Access to ecosystem service markets'
  },
  {
    'value': 'loans',
    'label': 'Low-cost loans'
  },
  {
    'value': 'support',
    'label': 'Farm support opportunities'
  },
  {
    'value': 'equipment_sharing',
    'label': 'Equipment sharing'
  }
