### ISSUE TITLE
Can't join from Group Details page

### ISSUE THREAD

**Issue by lorenjohnson** [Hylozoic/hylo-evo#1197]
On the current staging deploy of Farm in the Group Explorer Group > Group Detail View when I click on “Request to Join” (or any of its variants) nothing appears to happen.  Can someone confirm if they are having that or a different experience?
When I click on any of the URIs in under the “AT A GLANCE” section at the top of the Farm Group Detail for a generated Farm the URL is getting treated as a path into Hylo not as an external URL.

**Comment by thomasgwatson** [comment]
I'm a little confused because would have expected the join button to be here but its not... Is this where it usually goes?

![image](https://user-images.githubusercontent.com/5193218/167954078-a92a1557-0fff-47c4-a8d1-df6b0a0c3286.png)

**Comment by lorenjohnson** [comment]
It's consistently appearing for me on non-farm groups, maybe not on farm groups?
