### ISSUE TITLE
Next steps with Text formatting of posts

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1235]
We will take the next steps to enable easy text formatting in posts. This may include:
- [x] h1, h2 and h3 options
- [x] Bulleted Lists
- [x] Numbered lists
- [x] List indent/outdent buttons and/or key shortcuts?
- [x] Strikethrough text
- [x] An always visible formatting bar
- [x] Key shortcuts like ⌘-b for bolding and unbolding text
- [x] Pasted in text retaining formatting
- [ ] Bold text displaying more bold

**Comment by lorenjohnson** [comment]
Did a reprise of earlier research and came to same conclusion as earlier rounds: Probably going to move us to Slate/Plate editor, or maybe Prosemirror/TipTap...
