### ISSUE TITLE
Welcome message isn't saving after editing

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1249]
A user reached out about the Welcome Message on the Explore page not saving. I tested it out and am having the same issue. Neither the title nor description save after being edited + saved.

**Comment by KrishaTerranIO** [comment]
Hey Tom, I'm still having trouble with editing and saving a welcome message. Is there something different I should do on my end? I refreshed my browser.

**Comment by thomasgwatson** [comment]
It's not deployed, just merged to dev
