### ISSUE TITLE
Invite links not working

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo-evo#1256]
Users have shared this invite link `https://www.hylo.com/groups/compass-network/join/YdlnIxFHP` but it navigates to a page that shows the hylo loading widget.

This functionality worked on my local dev env; but not in production.

Invite by email still seems to work.

Error/warning in Prod that might be related:
`Request to access cookie or storage on "https://bam.nr-data.net/1/769f5b960a?a=89975482&v=1216.487a282&to=NARRNUZXX0NWUUBaCw1OcBRHQl5dGB0%3D&rst=1632&ck=1&ref=https://www.hylo.com/groups/compass-network/join/YdlnIxFHP&qt=1&ap=4.011406&be=467&fe=1426&dc=926&tt=2cc445de69e88ac8&perf=%7B%22timing%22:%7B%22of%22:1658337980180,%22n%22:0,%22f%22:-47,%22dn%22:51,%22dne%22:243,%22c%22:243,%22s%22:255,%22ce%22:286,%22rq%22:286,%22rp%22:448,%22rpe%22:450,%22dl%22:454,%22di%22:921,%22ds%22:925,%22de%22:926,%22dc%22:1425,%22l%22:1425,%22le%22:1426%7D,%22navigation%22:%7B%7D%7D&fcp=669&jsonp=NREUM.setToken" was blocked because it came from a tracker and content blocking is enabled.`

![Image](https://user-images.githubusercontent.com/5193218/180313362-ac93bf43-2307-4491-9fbb-75b9235381c2.png)

**Comment by tibetsprague** [comment]
that warning is about new relic and shouldnt prevent anything else from working i dont think

**Comment by tibetsprague** [comment]
turns out they just reset the invite link and the old one doesnt work!
