### ISSUE TITLE
Handle broken invite links better

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1260]

**Comment by tibetsprague** [comment]
When trying to use a broken invite link there should be some kind of error message that appears. Maybe? right now it redirects to last page you went to in hylo, and can have weird behavior

**Comment by thomasgwatson** [comment]
@tibetsprague 

The page does a try/catch. On error (catch), it does `history.back()`. Added a window.alert to explain what is happening but could also build out an actual warning page instead, and redirect to that. What do you think?

![Image](https://user-images.githubusercontent.com/5193218/181373480-54d57403-16b8-45e9-bfe7-a8f5f1afad8c.png)

**Comment by tibetsprague** [comment]
This is a fine MVP. history.back is a little odd though because it could go to a non Hylo page if you just copy it into the URL, so I think we should just redirect to baseUrl()
