### ISSUE TITLE
Resetting invite link should have a confirmation dialog

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1261]
To make sure people know that old links will stop working

**Comment by thomasgwatson** [comment]
Already does. Assuming we don't need this ticket.

![Image](https://user-images.githubusercontent.com/5193218/181345370-10f2b143-e0bd-4f47-89e5-42de9341e636.png)

**Comment by tibetsprague** [comment]
Oops, hah should have checked. Thanks!
