### ISSUE TITLE
Issues with chronology on post date/latest activity

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1273]
When on mobile and desktop, there were issues with the chronology of posts when sorted by latest activity and post date. I have been testing this and sometimes have issues and other times the stream displays correctly. Unsure if the latest updates fixed the issue because I'm not experiencing them now. 

Pinned posts only stick to the top of a stream when a channel is sorted by "Latest Activity," not "Post Date" or "Popular"

<img width="776" alt="image" src="https://user-images.githubusercontent.com/92816219/186479016-da32daf7-eb7a-43e5-b479-00e31de3ebc3.png">

**Comment by KrishaTerranIO** [comment]
UPDATE: chronology for latest activity is definitely wonky. When sorting Building Hylo by latest activity, getting a post from a year ago popping up first on the stream. 

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/92816219/188943540-fb12c443-ae02-471c-a22a-aea43a061e10.png">

**Comment by tibetsprague** [comment]
I think it pops up if someone upvotes it along with new comments of course. 

Sent by m

**Comment by KrishaTerranIO** [comment]
Gotcha, that's helpful context and makes sense!
--
*Krisha Subramanian (she/her)*
Stakeholder Advocate
***@***.***
Coastal Miwok Territory/San Francisco

Terran Collective <http://terran.io/>: *Amplifying cooperation among people
working to regenerate our communities and our planet, by building systems
and tools that foster trust and collaboration.*

Hylo <https://hylo.com/>: *The Social Coordination Platform for a Thriving
Planet*
