### ISSUE TITLE
Add search/filter to views

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1284]
- [x] Add new Search tool to StreamViewControls. Clicking a magnifying glass button will open up a search bar like at the top of the Map drawer, except without all the topics options shown. You can add search terms by entering one and hitting enter and the search bar will disappear and the search term will show at the top of the stream and the stream will be filtered by that term. 
- [x] Get rid of the Feed, FeedList and all Feed components and use the Stream component everywhere (rename FeedBanner to StreamBanner?). Right now Topics use FeedList, as does the Projects view. And the Events view might also want to be merged into Stream? Maybe. 
- [x] Relatedly add StreamViewControls to Projects view and CustomViews, so people can change the View mode/style and sort for those views if they want. Default to the current settings. For Custom Views the Post Type filter selector will only show Post Types that are being shown on the Custom View.

**Comment by thomasgwatson** [comment]
![image](https://user-images.githubusercontent.com/5193218/192338040-13024247-d780-40ec-a057-25a0b11f9442.png)

new search replaces the old search

**Comment by thomasgwatson** [comment]
Search icon to the right of the view pickers

![image](https://user-images.githubusercontent.com/5193218/192338346-283c07c9-9cf7-4ef8-a04b-7326cf18a8ce.png)

**Comment by thomasgwatson** [comment]
Where does the search bar pop up?
Does it stay after the search has been entered?
Does the search result replace the search bar or where will it go?

**Comment by thomasgwatson** [comment]
Search available

![image](https://user-images.githubusercontent.com/5193218/192402387-02c55734-6879-428d-aec9-69a2efe269b2.png)

Search active

![image](https://user-images.githubusercontent.com/5193218/192402449-48e7728c-1dca-4643-b0b0-054bb314132f.png)

Search selected

![image](https://user-images.githubusercontent.com/5193218/192402483-6f8586d6-e174-4cf7-894d-83c424c4eba6.png)

**Comment by tibetsprague** [comment]
This looks great! Aaron can do a final pass
