### ISSUE TITLE
Public Posts need Meta Tags to generate Link Previews

### ISSUE THREAD

**Issue by cpolitano** [Hylozoic/hylo-evo#1285]
When public posts are shared on FB, TW, Discord, etc, there should be polished link previews with images, title, and description that appear, so people have a sense of what they are clicking on.

**Comment by thomasgwatson** [comment]
I've used `React-Helmet` for this in the past and it is the overwhelmingly preferred community option. https://www.npmjs.com/package/react-helmet

Propose we add this to EVO @tibetsprague @lorenjohnson

**Comment by tibetsprague** [comment]
Sounds good to me! I also would love to use it to customize page titles across the app so that different Hylo tabs show the actual page info in the title

**Comment by lorenjohnson** [comment]
Yes, this would be great! Please do that. This is critical for making the App sharing nice, hence why I was giving it extra nudges today. Both Link Previews within Hylo Web and Sharing out of the App will thank you very much :) We'll look better.
