### ISSUE TITLE
 Marker that shows all posts that are "new" to you since you last looked

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1305]

**Comment by thomasgwatson** [comment]
What data could back this feature?

I feel like there are a few things I've seen around the code base (like even the little number thingy in the left group nav)

![Image](https://user-images.githubusercontent.com/5193218/199118127-5bf53201-4643-4eb9-909d-7515643de529.png)

**Comment by tibetsprague** [comment]
I also think this is something I should do since im deep in this work
