### ISSUE TITLE
Post Title length error popup causes awkward resize of Toolbar in PostEditor

### ISSUE THREAD

**Issue by lorenjohnson** [Hylozoic/hylo-evo#1327]
Maybe put small text right below the title and push everything down?

**Comment by lorenjohnson** [comment]
![Screen Shot 2022-10-23 at 4 34 00 PM](https://user-images.githubusercontent.com/6294/197423674-323c8525-6268-45d1-815d-7adeb09e2ea7.png)

**Comment by KevinTriplett** [comment]
@lorenjohnson and/or @tibetsprague here's a screenshot of my first pass. The datepicker uses the same style so I split it out for the two (hence the two screenshots, to show that the datepicker error will not be affected after merging the PR).

_**Also, the datepicker error placement is even worse than title "error" placement -- I suggest combining the two in this issue or feel free to open a new issue and assign it to me.**_

### Title error message
I changed the color and wording from a statement of error to one of warning

**Roomy:**
<img width="564" alt="Screenshot 2024-04-09 at 10 22 31 AM" src="https://github.com/Hylozoic/hylo-evo/assets/5772/77932242-38fd-4bc8-8f0f-8b5987a573c8">

**Squozed:**
<img width="408" alt="Screenshot 2024-04-09 at 10 22 44 AM" src="https://github.com/Hylozoic/hylo-evo/assets/5772/c3a39ffa-bc5c-4661-a194-b63e645f8544">

### Oops -- datepicker error needs to be fixed too

**With calendar still open**
<img width="556" alt="Screenshot 2024-04-09 at 10 24 07 AM" src="https://github.com/Hylozoic/hylo-evo/assets/5772/92e90f63-b835-4e3d-a096-e4315bccf85c">

**With calendar closed**
<img width="552" alt="Screenshot 2024-04-09 at 10 24 15 AM" src="https://github.com/Hylozoic/hylo-evo/assets/5772/d7365917-efeb-4130-a787-03f0aa1e797b">

**Comment by KevinTriplett** [comment]
One more change I'd like to propose for this issue (or a separate issue):

Problem: When a post whose title is already at maxLength, the input does not fire the onChange event despite the user banging on the keyboard. No feedback.

User workaround: Delete a character and then type a new character, now they know. (suboptimal)

Proposed: on initial render, set the error flag when title is at MAX_TITLE_LENGTH. This renders the Modal with the warning already displayed. Now the user has indication of why they can't change the title.

**Comment by KevinTriplett** [comment]
Here's a screenshot of my fix for the datepicker error unfortunate placement:

<img width="505" alt="Screenshot 2024-04-09 at 10 36 07 AM" src="https://github.com/Hylozoic/hylo-evo/assets/5772/da4e28db-b5bb-4e92-b427-469bf6fbdb38">
