### ISSUE TITLE
Update UX and UI for showing child group posts in current groups Stream

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1331]
Add a toggle to streams to decide whether to show posts from child groups you are a part of or not.

Do we save this across all groups like we do other streams settings right now?

**Comment by tibetsprague** [comment]
Default to posts from child groups not showing.
Filter at the top of the stream to turn on child posts showing which is saved as a global user setting like other stream filters.
But what does it look like and what does it say?
Also have a user setting that does the same thing?

**Comment by tibetsprague** [comment]
how does this effect Events, Projects & the Map which also currently show child posts?

**Comment by tibetsprague** [comment]
can cherry-pick started work on this from 1301-chat-rooms, commit a22ed51a00045c5ffb48222a51ce3f2614e71394

**Comment by cpolitano** [comment]
hey @thomasgwatson @brodeur here's what we decided:
It's a global user setting that is controlled in Personal Settings. Default is OFF (child posts are not shown)
If the setting is turned ON, child posts are shown in Stream, on Map, in Events, Projects, and anywhere else we were showing content from child groups
If the setting is turned ON, a pill label appears on the stream with a label like "Aggregated Posts" and a tooltip that says on hover: "You are seeing posts from this group and subgroups. You can adjust your content aggregation in Personal Settings."
Child posts receive a special design treatment (design tbd) and a label saying "This post comes from subgroup X"

@tibetsprague @KrishaTerranIO did I miss anything?

**Comment by thomasgwatson** [comment]
@cpolitano do we feel able to push forward on this one or shall we wait for a little bit of the community input from that hylo post you made? https://www.hylo.com/groups/building-hylo/post/53971

**Comment by tibetsprague** [comment]
i think we are ready to move forward though still needs some design from @brodeur on all the pieces of it. you could do a first version of aaron to react to though

**Comment by KrishaTerranIO** [comment]
@cpolitano @brodeur @tibetsprague 
In our call with Prosocial this AM, they specified that they want this to be a user feature 
rather than a moderator privilege, and requested a simple toggle on the user stream "Hide/Show" [child posts].

**Comment by KrishaTerranIO** [comment]
Update from Product Nov 16

Content aggregation is going to be a user setting, with a toggle "hide/show" in the Stream, Projects, Events, and Map. 

Default setting is child posts show.

**Comment by tibetsprague** [comment]
and indicate in child posts that they are coming from a child
