### ISSUE TITLE
Continuation to link after signing-in issue

### ISSUE THREAD

**Issue by lorenjohnson** [Hylozoic/hylo-evo#1342]
It seems like going to `/post/:postId` is going to the “Oops, there’s nothing to see here!” Axolotl Page when I'm not logged-in and navigate to an otherwise valid Post URL (e.g. https://www.hylo.com/post/51727)

When I go to the same group scoped URL at https://www.hylo.com/groups/building-hylo/post/51727 I don't get an error, and am just forwarded to the Login page, which is what I’d expect. My last revamp of the routing included this behavior, and a `returnToPath` auth continuation workflow (see note here https://github.com/Hylozoic/hylo-evo/blob/dev/src/routes/NonAuthLayoutRouter/NonAuthLayoutRouter.js#L97 and feel free to ask me to fill you in more on that / how that's SUPPOSED to work).

However, once I logged-in it didn’t seem to route me back to the Group or Post, which I didn’t expect. 

The  v5.1.0 of the App which is going out in the next day or two is using the `/post/:postId` basis for the new “Copy Link” and "Share" actions.  Perhaps even more critically, we need to check-in on this as it may mean that Join and/or Notification links may not not be continuing to the intended place after auth...

--- 

\* I suspect there are in fact be two separate issues here. One with the `/post/id` URLs (see this line: https://github.com/Hylozoic/hylo-evo/blob/bb8b7fe502a6a10689cde0f55266c9ac79334abd/src/routes/RootRouter/RootRouter.js#L59 -- I think this needs amending 
...and the other more general issue with the `returnToPath` stuff linked above. Both would need to be addressed for `/post/:postId` links to work if the post wasn't public.

**Comment by thomasgwatson** [comment]
So the recent changes are now `/post/:id`. Did we want to flick over to the plural `/posts/:id`?

**Comment by lorenjohnson** [comment]
Oh sorry. That's my bad and I just had it wrong. Need to make sure I didn't get that wrong in my the App! But no I think for now it's fine if `post/:postId` redirects or is invalid, either way.

I think continuation is still not work though.

**Comment by lorenjohnson** [comment]
yes imho `posts/:postId` is the correct route but now i'm getting confused about what is actually implemented... always plural is my religion when it comes to routing object names, but i'm also fine if the singular and plural form always do the exact same thing. it just can be an invitation to confusion to not settle on one.

**Comment by lorenjohnson** [comment]
Ah, I see. We have been using the the singular `/post/:postId` so no matter what we do that needs to remain valid. So actually nvm my my remarks about plural in this case. Let's just keep `/post`. If someone wants to jump on the plural bandwagon with me then let's get that right now, otherwise we'll just let it stay the way it landed. Sorry for the confusion on that part.

**Comment by tibetsprague** [comment]
Hmm https://www.hylo.com/post/53933 is working for even when I am not logged in, what do you see @lorenjohnson ?

**Comment by tibetsprague** [comment]
if we go plural then I think we should change it in the details URLs too like /groups/xxx/posts/xxx, but this will require some serious auditing of the app. I think there are places we depend on looking for the singular /post in the URL and maybe the singular /group too. Is this the moment for a major audit and update all our URLs... I feel nervous about that, but we can discuss as a team.

**Comment by tibetsprague** [comment]
ah yes I see what you mean, going to a non-public post like https://www.hylo.com/post/45645 should go to the login page immediately and then redirect to that post

**Comment by lorenjohnson** [comment]
Yes, the logic I wrote I the other ticket is what I think should be happening. That was pretty thought through and I think we shouldn't be doing less than any of that otherwise we'll be regularly re-visiting it and otherwise making something confusing or brittle.

`post` vs `posts`: Yeah... I do think plural would best best everywhere all the time, and should be what we do, but I wouldn't want making that correction to distract from getting the basic logic right today. For posts, since there are not posts within posts (yet 🤷🏼‍♂️) the recursive issues are not really a concern for me. For groups it's already kinda came-up and `/groups/:parentGroup/group/:childGroup` routes I do think are going to cause use extra headaches.

**Comment by lorenjohnson** [comment]
> Hmm https://www.hylo.com/post/53933 is working for even when I am not logged in, what do you see @lorenjohnson ?
> ah yes I see what you mean, going to a non-public post like https://www.hylo.com/post/45645 should go to the login page immediately and then redirect to that post

Yeah, this ticket is about what happens when a user is trying to access a non-public thing when they're not yet authenticated, and whether they get forwarded to that thing after they have authenticated. 

A nice thing generally, but our Sign Up with a group invite relies on it working right. It seems to have broken at some point and I think is worth prioritizing an exploration/fix.

**Comment by thomasgwatson** [comment]
I just tested `/post/:postId` when non-logged-in, for a post my user had access to. It directed me to sign-in, and then redirected me to the right post. 

Can we close this issue?
