### ISSUE TITLE
My Home context

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1382]
- [ ] New context appears in its own section, above the Public section. My Home?
- [ ] New navigation menu in this context:
- [ ] @Mentions - posts I've been mentioned in - default to sort by Post Date
- [ ] Interactions - posts I've commented on or reacted to  - default to sort by Post Date
- [ ] My Posts - posts I've created  - default to sort by Post Date
- [ ] Announcements- across all groups I'm in  - default to sort by Post Date
- [ ] Offer same filter/sort bar as other streams

**Comment by KrishaTerranIO** [comment]
Above public stream/groups/map, icon that says "my inbox", when you click on it, the interface is the same as if you were clicking on Public Stream, Groups Map
The side nav will be gone and there will be three new items in this order: #mentions, #interactions, #announcements, and "My Posts" 

Sorting:
Default by Date (most recent first)
Same sorting mechanisms as in the other streams
Filter:
By post type

**Comment by brodeur** [comment]
<img width="1203" alt="Screen Shot 2022-12-01 at 9 04 33 AM" src="https://user-images.githubusercontent.com/83412/205115293-16294d09-1fe7-43a1-bf5f-3a23a42c3f95.png">
https://www.figma.com/file/XtXvB21mSogx16n1QGLsoR/My-Stuff-%2F-Home?node-id=0%3A1&t=4sldqu591S5OGT3d-1

**Comment by thomasgwatson** [comment]
@tibetsprague @brodeur 
Where do these links actually lead?

![Image](https://user-images.githubusercontent.com/5193218/207454615-9aecd45b-2699-4c48-8684-0c05f0b955cf.png)


Will it just be reusing the Stream component, with a specific query?

**Comment by thomasgwatson** [comment]
Will each of these options track 'unread' or 'new posts' or something like that?

**Comment by tibetsprague** [comment]
@thomasgwatson as far as i know these will just display feeds, though we should decide what the header looks like and says for each one
