### ISSUE TITLE
When clicking on a Topic you always land at the Top of the stream

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1402]
When clicking on a topic on the web app, you land at the top of the stream and have to scroll to the bottom. If you return to that Topic, you still land on the top of the stream. This happens with all topics. 

I tested this in other groups and found the issue to persist.

**Comment by tibetsprague** [comment]
this is not actually happening for me. the first time I load a topic it is taking me to the top, which is probably not what we want, but not sure we can do much about that right now, more to think about. but then if I scroll down the next to I load the page or go to the topic it is taking me down to about where I was. it does seem to be one post off though, which I think was actually on purpose, and works well for chat posts (so you see last post above the new one) but when the posts are full post cards it feels slightly off to go to the one above

**Comment by tibetsprague** [comment]
but @KrishaTerranIO id love to double check what is happening for you since I cant reproduce

**Comment by KrishaTerranIO** [comment]
Uploaded a video from this AM. 
https://user-images.githubusercontent.com/92816219/209252452-decd2d91-3d06-40b0-8d45-7b061f34a1f0.mov

Though when I went back it's no longer happening?
