### ISSUE TITLE
Hello! An xmas request

### ISSUE THREAD

**Issue by richchurcher** [Hylozoic/hylo-evo#1403]
Happy holidays :christmas_tree: from a past Hylo-ite :sunglasses: hope you're all doing well.

Could someone possibly go into the various App Store/TestFlight/other mobile pipelines and yoink my email address out of there? I get quite a few notifications regarding mobile releases, and I probably don't need to be getting those any more :laughing:

**Comment by lorenjohnson** [comment]
Hi @richchurcher! For sure, I've taken care of that now. Happy holidays way over there! 🎄 And let us know if any other things you may still be on you want to be removed from
