### ISSUE TITLE
User report of repetitive notification from comment mention

### ISSUE THREAD

**Issue by lorenjohnson** [Hylozoic/hylo-evo#1406]
User is reporting receiving the same notification repetitively from comments in this Building Hylo thread:

https://www.hylo.com/groups/building-hylo/post/55033

Original report is here:

https://www.hylo.com/groups/building-hylo/post/55253

"Been getting a notification for the same comment maybe every day now for a while, sometimes more than once, specifically the comment from Jakob on the ChatGPT post in case that's helpful for tracking it down."

**Comment by tibetsprague** [comment]
i think i fixed
