### ISSUE TITLE
User cannot create a post on Hylo (can fill out all the information, but cannot Post)

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1415]
User is unable to create posts on Hylo. He can comment on existing posts. 

User is using a Macbook Air. They can fill ou all the information in the Create modal, however when they try to click "Post" they see  a circle with a line thru it.

User is using Google Chrome and has McAfee Total Protection installed
His email is: kurtjohnsonisd@yahoo.com

We are waiting for screenshots and for him to test turning off/pausing McAfee services and seeing if posting works.

**Comment by tibetsprague** [comment]
Make sure he knows he has to add a title to the post.
