### ISSUE TITLE
Display group roles/badges

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1434]
- Member profile when in a group context
- Next to other groups listed on the profile?
- Next to person's name throughout the app?
- Member directory card
- Filter/search member directory by role/badge
- Display Moderator as a badge too (first badge)

**Comment by brodeur** [comment]
Move this to new roles & badges section

![Image](https://user-images.githubusercontent.com/83412/214662196-f819eb61-5e12-4aac-a8f7-4ec96ceeb994.png)

**Comment by thomasgwatson** [comment]
Splitting the above into a separate ticket. It will require a little more thought than just moving some UI around
https://github.com/Hylozoic/hylo-evo/issues/1444
