### ISSUE TITLE
Mark edited posts and comments as "edited"

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1439]

**Comment by KevinTriplett** [comment]
@brodeur I'd love your input on how to style this. These are the two ideas I have, browser and mobile versions:
This one shows only posted or edited timestamps
<img width="665" alt="Screenshot 2024-07-11 at 3 16 10 PM" src="https://github.com/user-attachments/assets/89791323-90f2-492b-96b8-d816aa0d66f1">
This one shows both posted and edited timestamps
<img width="662" alt="Screenshot 2024-07-11 at 3 15 53 PM" src="https://github.com/user-attachments/assets/b8c51c89-635b-422f-a9fd-0f4d7b26e822">
Here are the mobile versions:
<img width="414" alt="Screenshot 2024-07-11 at 3 17 45 PM" src="https://github.com/user-attachments/assets/f8e89ad9-92fe-45ae-8786-96bd89cfc60d">
<img width="394" alt="Screenshot 2024-07-11 at 3 18 17 PM" src="https://github.com/user-attachments/assets/4704fc59-9071-46ef-b092-46335868c2b9">

**Comment by KevinTriplett** [comment]
For list view, I think going with either and not both:

<img width="410" alt="Screenshot 2024-07-11 at 3 56 55 PM" src="https://github.com/user-attachments/assets/139a3271-e5fd-4824-91c3-dc0a4e5eb378">

**Comment by KevinTriplett** [comment]
For the grid views, should we keep the createdAt timestamp or editedAt?

<img width="729" alt="Screenshot 2024-07-11 at 4 03 27 PM" src="https://github.com/user-attachments/assets/4e4b6fb4-c582-4d98-bc06-a0d2bc546caf">

<img width="485" alt="Screenshot 2024-07-11 at 4 03 34 PM" src="https://github.com/user-attachments/assets/82d7f5a4-29e1-42c0-9cc5-06bbd5f3d54e">

**Comment by tibetsprague** [comment]
another option is to put (edited) at the bottom of the content itself, like Slack does, separate from the post creation timestamp

**Comment by KevinTriplett** [comment]
I deleted the previous screenshots to reduce noise -- here's the current styles:

<img width="604" alt="Screenshot 2024-07-14 at 8 55 16 AM" src="https://github.com/user-attachments/assets/ec339511-4bc5-4506-b783-3d7f186fc387">

<img width="643" alt="Screenshot 2024-07-14 at 8 55 03 AM" src="https://github.com/user-attachments/assets/d066ff08-5d7f-4f57-937a-e48676760332">

<img width="633" alt="Screenshot 2024-07-14 at 8 54 57 AM" src="https://github.com/user-attachments/assets/24e0bafd-7da5-401d-aed8-cfaa728754a4">

<img width="614" alt="Screenshot 2024-07-14 at 8 56 06 AM" src="https://github.com/user-attachments/assets/362c14b4-9d62-4256-9f4a-a3c1eae80cfe">

<img width="681" alt="Screenshot 2024-07-14 at 8 56 27 AM" src="https://github.com/user-attachments/assets/cfb7a562-a672-4b7d-bd0d-3cf9ecf8d9d8">

<img width="676" alt="Screenshot 2024-07-14 at 8 56 18 AM" src="https://github.com/user-attachments/assets/7347f611-a22c-44ee-9e48-c7b35abe95cf">

<img width="459" alt="Screenshot 2024-07-14 at 8 56 41 AM" src="https://github.com/user-attachments/assets/b102d4d4-5e1e-47ae-b92d-925c717bc8ba">

<img width="454" alt="Screenshot 2024-07-14 at 8 56 59 AM" src="https://github.com/user-attachments/assets/c84a2eda-c888-4397-9d35-109eed60018b">

**Comment by KevinTriplett** [comment]
For comparison, here's a screenshot from Mighty Networks in list view:

<img width="727" alt="Screenshot 2024-07-11 at 10 55 20 PM" src="https://github.com/user-attachments/assets/b04e0e11-b85b-4126-9047-e548204c1491">

**Comment by tibetsprague** [comment]
Some notes:
- let's move the Updated At above the emojis, and closer to the content. Indented at the same level as the content
- Let's call it Edited At instead of updated at
- We don't need to show Posted At a second time, if it hasnt been edited, dont show anything there
- In the grid views we also want to add Edited At, right at the bottom of the content. Same in list view

**Comment by KevinTriplett** [comment]
Great suggestions, I'll make them and then push the changes. FYI, I was just about to change the wording to "Edited" (dropping the "at" I feel it's unnecessary and shortens it).

**Comment by KevinTriplett** [comment]
Note: grid view has only the `humanDate` format because in mobile anything longer truncates the user's name. Let me know if this is a don't care and I'll add it.
