### ISSUE TITLE
Comments in a topic based chat not displaying

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1446]
Some strange behavior in a topic based chat. I am not a member of the group, though I could go to the comment and add a reply. However, my reply didn't save. When I went back, I saw additional comments from another member mentioning that the same issue was occurring for her. 

I'm unable to copy a link to the chat (assuming that it's becuase we can only copy a link to a post)

https://user-images.githubusercontent.com/92816219/215871913-d689ed16-fc1c-4abe-87a1-018e9abbcf47.mov

<img width="565" alt="image" src="https://user-images.githubusercontent.com/92816219/215871944-2cdb96de-914f-4ad3-9b69-dd0383be7a05.png">

**Comment by tibetsprague** [comment]
Yeah the real issue is you shouldn’t be able to see the post in a group you are not a member of, gotta fix that one!
