### ISSUE TITLE
Alignment off in the Create Post module (Post iN)

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1451]
<img width="641" alt="Screenshot 2023-02-07 at 5 24 42 PM" src="https://user-images.githubusercontent.com/92816219/217389856-7efba4eb-525a-403e-8acf-755749ed0b17.png">

The alignment is off between "Post In" and "Type Group Name"

**Comment by tibetsprague** [comment]
only happens when no groups are selected

**Comment by tibetsprague** [comment]
This is in src/components/GroupsSelector/GroupsSelector.js
