### ISSUE TITLE
Strange exclamation point in emoji reactions

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1455]
Edward West shared a screenshot of an ! in front of the number denoting the quantity of emoji reactions. This occurred on a Mac OS 11.4, Firefox v 109.0.1 (64-bit)

 Will share additional notes as I have them. 

<img width="505" alt="Screenshot 2023-02-13 at 10 59 17 AM" src="https://user-images.githubusercontent.com/92816219/218522847-ae32dc02-448a-4987-9d71-d4127a98012f.png">

**Comment by tibetsprague** [comment]
havent heard of or seen this recently, so maybe close?

**Comment by KrishaTerranIO** [comment]
I haven't seen it recently either, will close out now
