### ISSUE TITLE
Editing a chat on a topic stream - content disappears when the text box is filled. 

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1473]
If I fill up the entire space of the chat box, whatever I added disappears. I'm able to reproduce it and can add additional videos for context. This is happening on my mac google chrome browser.

https://user-images.githubusercontent.com/92816219/226779724-2fbc62f5-bb5f-492f-9265-79bc890a177d.mov

**Comment by KrishaTerranIO** [comment]
I wonder if this is the same issue? @tibetsprague 

I was adding a comment and it wouldn't let me press enter to send it. I had to copy the message, delete it, and paste it to send. 

https://user-images.githubusercontent.com/92816219/227386363-f533fa44-56b6-4f42-b17d-e52c4e398f69.mov

**Comment by tibetsprague** [comment]
is this still happening krisha! couldnt reproduce just now

**Comment by KrishaTerranIO** [comment]
haven't experience this recently, i think we can close this
