### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1492]
babel-plugin-i18next-extract: Extraction error in /Users/tibet/Dev/hylo/hylo-evo/src/components/Widget/OffersAndRequestsWidget/OffersAndRequestsWidget.js at line 28. Couldn't evaluate i18next key. You should either make the key evaluable or skip the line using a skip comment (/* i18next-extract-disable-line */ or /* i18next-extract-disable-next-line */).

babel-plugin-i18next-extract: Extraction error in /Users/tibet/Dev/hylo/hylo-evo/src/components/StreamBanner/StreamBanner.js at line 50. Couldn't evaluate i18next key. You should either make the key evaluable or skip the line using a skip comment (/* i18next-extract-disable-line */ or /* i18next-extract-disable-next-line */).

**Comment by tibetsprague** [comment]
@thomasgwatson these are interesting ones to figure out as they are dynamic

**Comment by thomasgwatson** [comment]
Yeah, I think anything 'dynamic' has to be `t()` at its source, not on arrival at rendering.
