### ISSUE TITLE
Chat on mobile web view doesn't show 'send' button/icon (so can't submit)

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo-evo#1494]

**Comment by thomasgwatson** [comment]
![Image](https://user-images.githubusercontent.com/5193218/232868038-48b8f6e0-29d6-4bf8-99d8-f40d28deda0f.png)

CommentForm relies on an enter key stroke to submit. But mobile web view doesn't have that. Do we already have a way to detect this webview? Or should I just use a media-query to hide a submit button?

**Comment by tibetsprague** [comment]
I think comments should always have a send button. we can use the same one we use in the chat rooms.
 @brodeur thoughts?
