### ISSUE TITLE
Fix display of public posts when not logged in and group slug is in the URL

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1503]
It shows the group landing page, not the post. Works if you take the group slug out of the URL

**Comment by tibetsprague** [comment]
https://www.hylo.com/groups/building-hylo/post/60718
https://www.hylo.com/groups/edge-prize/projects/post/59671

The way its supposed to work is to check whether the post is public, and if it is then redirect to 
https://www.hylo.com/post/60718

**Comment by thomasgwatson** [comment]
So you want it to redirect?

**Comment by tibetsprague** [comment]
Yes
