### ISSUE TITLE
When creating a post (using Create), "Discussion" is misspelled

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1513]
Discussion needs another "s"
<img width="557" alt="Screenshot 2023-06-05 at 2 05 55 PM" src="https://github.com/Hylozoic/hylo-evo/assets/92816219/70223560-2f05-4651-84d9-2ab406033aff">

**Comment by tibetsprague** [comment]
Yikes, must have happened in the translations suff
