### ISSUE TITLE
Topic-based chat channels not loading from Notifications

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1548]
I'm finding that chat channels are loading extremely slowly/not loading at all from notifications. I've refreshed the page, closed Hylo and tried links again to no avail. I get a page with an endless spinning wheel.

This issue is occurring on Mac, on google chrome

**Comment by KrishaTerranIO** [comment]
The issue seems to have resolved. Load times are fairly slow, however.

**Comment by tibetsprague** [comment]
Definitely still something I am going to work onOn Oct 6, 2023, at 2:50 AM, KrishaTerranIO ***@***.***> wrote:﻿
Closed #1548 as completed.
