### ISSUE TITLE
Instructional message about post title

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1553]
Posts Title should have instructions that Titles are required in order to post

**Comment by KrishaTerranIO** [comment]
@thomasgwatson

**Comment by tibetsprague** [comment]
still wondering where this one actually is addressed

**Comment by thomasgwatson** [comment]
In:
https://github.com/Hylozoic/hylo-evo/pull/1562

Or do you want a little more? The title placeholder is changed to something
clearer and the post button has a tooltip has an explainer

**Comment by tibetsprague** [comment]
Ah, ok that should be enough
