### ISSUE TITLE
Help text on file uploads - limit is 6mb

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1560]
We should add help text for uploads on Hylo Posts to indicate that the file size is 6mb. When folks upload something larger, there is no clarification or pop up that indicates why they can't upload the file due to size.

**Comment by eatallyourdarlings** [comment]
Thank you. Would also appreciate clarity within the app around whether any cumulative storage limits apply to groups or individuals.

**Comment by KrishaTerranIO** [comment]
@eatallyourdarlings Hi Olive, we don't have cumulative storage limits at this time.
