### ISSUE TITLE
Removing blank/test farm groups

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1570]
Remove blank/test Farm Groups from Hylo (crowding the farm explorer)

**Comment by KrishaTerranIO** [comment]
Removing:
-Valli Farms x3
- NA Farms x2

**Comment by thomasgwatson** [comment]
> Removing:
> 
> * Valli Farms x3
> * NA Farms x2
> 
> <img alt="Screenshot 2023-11-15 at 6 32 55 PM" width="780" src="https://user-images.githubusercontent.com/92816219/283285639-13585028-50d5-4e71-91a0-1bff01c2a42d.png"> <img alt="Screenshot 2023-11-15 at 6 32 45 PM" width="789" src="https://user-images.githubusercontent.com/92816219/283285642-c050568a-ab37-41b0-be5b-f22258fc03bd.png">

Deleted.

Let me know if there are any more

**Comment by tibetsprague** [comment]
Still unclear to me whether we should be deactivating these farms, or just removing from public

**Comment by KrishaTerranIO** [comment]
The ones I shared are test farms I created when I was initially playing
around with SurveyStack. They are the first ones that pop up for me when I
go to the Farm Explorer and makes the stream of farms look janky IMO

--
*Krisha Subramanian (she/her)*
Stakeholder Advocate
***@***.***
Coastal Miwok Territory/San Francisco

Terran Collective <http://terran.io/>: *Amplifying cooperation among people
working to regenerate our communities and our planet, by building systems
and tools that foster trust and collaboration.*

Hylo <https://hylo.com/>: *The Social Coordination Platform for a Thriving
Planet*
