### ISSUE TITLE
Scroll not working in Group Settings 

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1592]
Uploading Screen Recording 2024-02-21 at 3.48.24 PM.mov…

I noticed today when toggling group settings that I was unable to scroll when in Group Settings (See video attachment). I'm trying to delete a group and can't scroll down to the delete button.

I'm working off my mac on google chrome.

**Comment by thomasgwatson** [comment]
Seems like the video didn't upload?

**Comment by tibetsprague** [comment]
seems to be working for me, and also the video didnt upload

**Comment by thomasgwatson** [comment]
I'm guessing its a small screen size. The left side of the page doesn't scroll right? So if the screen size is small, you might not be able to reach the bottom (delete) tab
