### ISSUE TITLE
Unable to delete member profile 

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1593]
Hello,

An individual reached out via intercom about not being able to delete their profile. Just tested this on my end and wasn't able to delete a test account. This happened on my macbook in chrome.

https://github.com/Hylozoic/hylo-evo/assets/92816219/460341d6-6a4b-471a-83d4-b6d644b040a5

**Comment by tibetsprague** [comment]
I believe i just fixed this, can you test again?
