### ISSUE TITLE
chat channel goes blank after sending a chat

### ISSUE THREAD

**Issue by cpolitano** [Hylozoic/hylo-evo#1604]
After writing a chat and sending it, the screen goes white and this error appeared in the console:

<img width="642" alt="Screenshot 2024-03-26 at 9 41 37 PM" src="https://github.com/Hylozoic/hylo-evo/assets/5813534/a9ae8d65-749e-4ca0-a0a1-60bce7ac29b2">

I was in this group: https://www.hylo.com/groups/team-bioregional-finance-project/topics/general

**Comment by cpolitano** [comment]
This behavior did NOT happen when I went to another group (Hylo GC) and sent a chat there. Separately, a few members of this group have had issues where they click on the general chat channel and the page is stuck with a spinner and doesn't load.

**Comment by tibetsprague** [comment]
i hope/believe I have fixed this. let me know if you see it again
