### ISSUE TITLE
Remove get() and curry() calls from getRouteParam

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1609]
get can be replaced by ?. and curry seems like its not being used? will have to test everywhere where getRouteParam is called

**Comment by KevinTriplett** [comment]
May I also remove the state argument, since it's not used -- which means removing all the nulls from the calls.

**Comment by tibetsprague** [comment]
Sure On Apr 9, 2024, at 8:09 PM, Kevin Triplett ***@***.***> wrote:﻿
May I also remove the state argument, since it's not used -- which means removing all the nulls from the calls.

**Comment by KevinTriplett** [comment]
Thanks -- I'm a bit lazy, so I did a regex search for any call to getRouteParam that used less than 3 arguments, which would indicate use of the curried function. Results:

`getRouteParam\([^,]+,[^,]+,[^,]+,[^,]+\)` matches 3 (this is where we pass in false for `warn` to suppress console.log warning message
`getRouteParam\([^,]+,[^,]+,[^,]+\)` matches all except the above 3
`getRouteParam\([^,]+,[^,]+\)` no matches
`getRouteParam\([^,]+\)` matches only the console.log warning (see below line)

```const getRouteParam = curry((key, state, props, warn = true) => {
  if (warn && !props.match) console.warn(`getRouteParam('${key}') missing props.match`). <=== matches this line
  return get(['match', 'params', key], props)
})

I share your concern, it's not like we're fixing a bug and may introduce one. We either leave it alone or make the code cleaner. Your call, I'll trust you and I can walk away from this issue.
