### ISSUE TITLE
Add modal keyboard events handling

### ISSUE THREAD

**Issue by KevinTriplett** [Hylozoic/hylo-evo#1654]
Problems:
1) The prev arrow is past the edge of the box and
2) the keyboard arrows don't work

**Comment by tibetsprague** [comment]
weird, I thought the prev arrow was working before

**Comment by KevinTriplett** [comment]
Ya, me too. I fixed the css now I'm trying to understand why the modal isn't receiving keyboard events.

**Comment by KevinTriplett** [comment]
For future reference, [I found this page salient](https://dev.to/colettewilson/how-i-approach-keyboard-accessibility-for-modals-in-react-152p)
