### ISSUE TITLE
Difficulty editing a comment in #topics stream

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1664]
In a #Topic stream, I went back to an older comment to edit it. Once I start typing text, it immediately erases it and moves around the page. 

https://github.com/user-attachments/assets/c77934c2-b1ad-4585-8452-d2524de43d7f

If I OPEN the comment, I'm able to edit it properly. 

This is happening on my mac

**Comment by tibetsprague** [comment]
I can reproduce this. 

Just a couple notes, we actually call these topic chat rooms, not topic streams, and what you are editing is a post, not a comment. Comments are only in the threads inside a post once you open it up.

**Comment by KrishaTerranIO** [comment]
Thanks Tibet, I'm editing our gitbook now and make sure all the content is
reflective of that

--
*Krisha Subramanian (she/her)*
Community Lead and Land Steward
***@***.***
Zapotal, San Ramon, Costa Rica

Terran Collective <http://terran.io/>: *Amplifying cooperation among people
working to regenerate our communities and our planet, by building systems
and tools that foster trust and collaboration.*

Hylo <https://hylo.com/>: *The Social Coordination Platform for a Thriving
Planet*
