### ISSUE TITLE
Add summary to event posts

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#1668]
For some reason event posts don't show summary text, they should

**Comment by KevinTriplett** [comment]
@tibetsprague I found out that `hideDetails` controls wether or not the text is shown. Removing this restores the summary but it may impact something else -- I don't know the history behind it. Advice?

It's set here: https://github.com/Hylozoic/hylo-evo/blob/12c9e125097c5c3c821ff7975b803c457cc1f04b/src/components/PostCard/EventBody/EventBody.js#L65

And referenced here: https://github.com/Hylozoic/hylo-evo/blob/12c9e125097c5c3c821ff7975b803c457cc1f04b/src/components/PostCard/PostDetails/PostDetails.js#L47

**Comment by tibetsprague** [comment]
yeah this was from before my time. seems obvious to just undo it. there must have been some UI reason that having the event summary text was deemed undesirable. maybe just a little testing needed.

**Comment by KevinTriplett** [comment]
Adding my notes here for posterity:

PostDetails uses the boolean `expanded` to control how much of the body to show. The same variable name is used elsewhere. The hideDetails was used in EventBody as a prop to PostDetails.
