### ISSUE TITLE
Post does not appear on stream after being posted

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1702]
In the past 30 minutes, I created 2 posts and both disappeared. I share the post, it pops up on the side of my group stream, but when I 'x' it out, it is no where to be found. I have refreshed the page and looked in "My Home" and it is nowhere to be found.

This is happening on my mac, on the chrome browser

**Comment by tibetsprague** [comment]
I see them both. Do you maybe have a filter on for it stream? Like only show discussions?On Aug 29, 2024, at 5:21 PM, KrishaTerranIO ***@***.***> wrote:﻿
In the past 30 minutes, I created 2 posts and both disappeared. I share the post, it pops up on the side of my group stream, but when I 'x' it out, it is no where to be found. I have refreshed the page and looked in "My Home" and it is nowhere to be found.
This is happening on my mac, on the chrome browser

**Comment by KrishaTerranIO** [comment]
I just checked again, after refreshing they display! Not sure what was happening on my end.
