### ISSUE TITLE
Not receiving notifications on Hylo DMs

### ISSUE THREAD

**Issue by KrishaTerranIO** [Hylozoic/hylo-evo#1710]
I don't receive notifications / red dot displaying on messages when receiving DM's. I have to manually open direct messages and check if I have new messages. This is happening on Chrome on my Macbook. I searched 'issues' for a ticket for this but I couldn't find one.

**Comment by tibetsprague** [comment]
duplicate of https://github.com/orgs/Hylozoic/projects/2/views/1?filterQuery=notifications&pane=issue&itemId=46706987&issue=Hylozoic%7Chylo%7C36
