### ISSUE TITLE
Post title component truncates title with special characters

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo-evo#408]
Not a big deal but want to log as an issue.

My title got truncated because I included special characters. It was meant to be "Communities <=> Food <=> The Land <=> Tech" but displays as just "Communities"

Not sure if the data was truncated on input or whether it is correctly submitted in the post form and just not rendered on display.

![Screen Shot 2020-04-18 at 11 50 43](https://user-images.githubusercontent.com/5193218/79667706-ee22dc80-816a-11ea-868b-cc404e2332bb.png)

**Comment by tibetsprague** [comment]
fixed on the backend!
