### ISSUE TITLE
Link URLs don't appear in Post text or Comments

### ISSUE THREAD

**Issue by cpolitano** [Hylozoic/hylo-evo#409]
Specifically Zoom links, for example:
https://zoom.us/j/97047050619

The link gets posted in the post description, then disappears from the post. There is no link preview generated.

Exact reproducible case:
- Go to calendar.google.com
- Find an event that has a Zoom link in the description, drag to select to zoom link and copy it
- Paste the link into the description of a new Hylo post
- Create the post
- See that the link disappeared

**Comment by tibetsprague** [comment]
i cannot reproduce this myself. @cpolitano can you try again?

**Comment by tibetsprague** [comment]
also Geoff of Pacific Integral says it is working for him now too :)

**Comment by cpolitano** [comment]
@tibetsprague  I'm seeing this issue still on staging. Steps to reproduce:
1) paste zoom link in post description. I used `https://zoom.us/j/694825317`
2) link preview shows up, cool
3) click X on link preview to delete link preview. Zoom link still visible in post description
4) click Post, zoom link does not appear in rendered post.

<img width="538" alt="Screen Shot 2020-06-01 at 3 40 56 PM" src="https://user-images.githubusercontent.com/5813534/83461840-91c80380-a41e-11ea-8554-730c408fdc73.png">

**Comment by tibetsprague** [comment]
Ok i can reproduce if I paste in the link that has a different font! then it wont show up in either the description or the comment. lets try this one: `https://zoom.us/j/694825317`

**Comment by lorenjohnson** [comment]
Just as you suspected @tibetsprague, the the issue was being caused by rich text pasting inot draftjs. Surprised this hadn't came-up sooner, and also a little surprised that the default in DraftJS is to try and carry across any formatting. Regardless, there is a simple flag to set to have DraftJS do the formatting sanitization on paste. Tested and fixed the problem.
