### ISSUE TITLE
Add time-frame (start and end times) to availability of requests & offers

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#415]
- [X] Add optional fields to requests and offers for when it becomes active and when it stops being available.
- [ ] TODO - decide how to handle posts that aren't yet active or have expired according to `start_time` and `end_time`
- [ ] Maybe: Show countdown on the post to show when it will end?

Pending design convo with @brodeur & @tibetsprague 

Depends on https://github.com/Hylozoic/hylo-node/issues/465

**Comment by cpolitano** [comment]
@tibetsprague @brodeur What happens to a post when the endTime is reached? do we still show it in the stream? hide it? delete it?

**Comment by tibetsprague** [comment]
related: https://github.com/Hylozoic/hylo-evo/issues/437
