### ISSUE TITLE
Add option for a Post to be marked Public

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#416]
To determine whether a post should be public or only visible in communities shared to.

- Only logged in users can create posts. 
- New posts must be posted in at least one community before they can also be selected as public.
- Not doing this for public post v0: There is a "Public" community that these posts are added to.
- This option is available for All post types

- [x] Add field to Post Editor to select Public in the communities dropdown
- [x] Style indication on posts of public vs private @brodeur 

Depends on https://github.com/Hylozoic/hylo-node/issues/466

**Comment by cpolitano** [comment]
- Waiting for styles from @brodeur on `Style indication on posts of public vs private`
- @tibetsprague re `Should we only add this to requests and offers or to discussions too?` I think this should apply to all post types. Sound good?

**Comment by tibetsprague** [comment]
one question that has come up is around where/how people can see public posts. Can they only see them in the map, and thus only posts that have a location? or is there also a stream view that shows all public posts anyone has posted anywhere in Hylo?

**Comment by tibetsprague** [comment]
Another concern is around moderation. Since we dont have a solid moderation system/plan yet there is a concern about inappropriate content being spread by trolls. we can mitigate this by requiring all posts to be sent to at least one community the person is a member of before it can be made public (which is currently already the case), then the community would handle moderation. however someone could create their own community and post publicly from there. perhaps we require people to post to a community that has at least 10 people in it? that would be a good way to start

**Comment by tibetsprague** [comment]
Questions for MVP:
1) Do we only show public posts in map view or do we have a public post feed view too?
2) if only on map then do we only allow people to make posts public if they have a location?
3) Do we require a post to go to a community that has a minimum # of people before one can post publicly?

**Comment by tibetsprague** [comment]
And posts without locations can also be public since we now have a public stream view
