### ISSUE TITLE
Allow for posting images or attachments in comments

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#442]
Depends on https://github.com/Hylozoic/hylo-node/issues/476

Design target:

https://www.figma.com/file/dC5VmXa5bqRAVunzumsMzy/Upload-images-in-comments?node-id=0%3A1&viewport=998%2C-696%2C0.7392762899398804

**Comment by lorenjohnson** [comment]
https://github.com/Hylozoic/hylo-node/pull/519
