### ISSUE TITLE
Update Android app to 64bit and get it back in Play store

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#443]
Real issue here https://github.com/Hylozoic/HyloReactNative/issues/322 but that cant be added to project until it that repo is open sourced

**Comment by lorenjohnson** [comment]
Update on this: Things are looking really good for an Android release shortly. The release build is finally working and building via Bitrise. I've ironed out all the bugs I can find in my own QA, and while it would be good to pass it around for wider QA, there is no Android release currently available so I realized it'd be better to just get this one out rehearsing the Google Play Store release process again in the process. 

We can iron out our mobile QA and automated build / release pipeline process with you all after that. 

As it is I should be able to have a good Android release tomorrow, or potentially Monday as I have some scheduling things that may not put me in-front of it tomorrow.

Hope that all makes sense.

**Comment by tibetsprague** [comment]
eep! so exciting :) I feel good about a release quickly and then more testing...
