### ISSUE TITLE
Can't save setting to let anyone invite people to the community

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#557]

**Comment by lorenjohnson** [comment]
@tibetsprague I have not been able to reproduce this. The setting is changing and saving in all communities I've tested both in local dev, and on production. Which community reported this originally?

**Comment by tibetsprague** [comment]
Yeah me too, I am going to talk with the guy who is struggling with it tomorrow. The community slug is circularfood

**Comment by tibetsprague** [comment]
the actual issue: https://github.com/Hylozoic/hylo-evo/issues/564
