### ISSUE TITLE
Load posts for map much more quickly

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#616]
Initial load of posts doesn't need all post data just type and name and location. 

Then have separate query to load posts for the drawer and load as you scroll

This means we will also need to use server side filtering for the drawer posts

Question: how many posts should we load on the map at first? eventually we want to load all, but that might require some server side caching or tile creation or something... maybe we can try loading all of them if we are just loading the very basic post info for the map

- [ ] Load more than first 100 posts, how many?

**Comment by wushenshen** [comment]
Now that the map drawer is expanded by default more than just the type, name, and location are needed. If the map drawer stays out as the viewport changes, same situation. Everything in the PostCard is needed for the posts in the viewport - so looks like the attachments, communities, isPublic, creator, timestamps, etc.

**Comment by tibetsprague** [comment]
not for the map, only for the drawer. that is the point of this ticket, only load the extra stuff in a separate query in the drawer, and only for the first 10 posts or so so it will be fast. for the map we want to load all the posts so we need minimal data to be faster
