### ISSUE TITLE
Events on iOS includes spurious Resource notice

### ISSUE THREAD

**Issue by geofffitch** [Hylozoic/hylo-evo#630]
On iOS event in feed, the notice "RESOURCE ENDS SEP 13, 2020" is given 

![IMG_D5B9F6DCFCA4-1](https://user-images.githubusercontent.com/6826098/92037653-f6993f80-ed26-11ea-9a3c-d8eef84a326e.jpeg)

**Comment by lorenjohnson** [comment]
Closing as covered in upcoming Events on Mobile implementation and tracked here: https://github.com/Hylozoic/HyloReactNative/issues/335
