### ISSUE TITLE
Text Formatting in Posts: Extra blank line added when single newline entered in post edit

### ISSUE THREAD

**Issue by geofffitch** [Hylozoic/hylo-evo#640]
Insert a line break in a post edit with the enter key. a new line is started with no space verticaly: 

![Screen Shot 2020-09-06 at 11 38 45 AM](https://user-images.githubusercontent.com/6826098/92332908-c6f37b80-f035-11ea-978b-be1eaf15a284.png)

But when the post is made, a vertical space is inserted. 

![Screen Shot 2020-09-06 at 11 39 20 AM](https://user-images.githubusercontent.com/6826098/92332902-bcd17d00-f035-11ea-9097-e502f5375f9a.png)

**Comment by lorenjohnson** [comment]
This is also true on Mobile.
