### ISSUE TITLE
New stream sort option that is just post created date

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#657]
By default still sort by activity but call it Latest Activity
Add new sort option that is Post Date

**Comment by lorenjohnson** [comment]
@tibetsprague Would this be to sort on post.created_at? 

* The post.updated_on is the current "Latest" sort and that tracks both post.title, post.description, and new comments on the post. We don't currently track a timestamp for just updates to post.title and post.description.

**Comment by tibetsprague** [comment]
Yes created-_at

Sent by m
