### ISSUE TITLE
Filter to just see "My Projects"

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#658]
Add filter to only show projects that the person has joined.

**Comment by lorenjohnson** [comment]
In the midst of implementing this as an additional option in the "Projects" area as an additional feature. For a couple of reasons I am feeling this feature may be best added as a profile addition (perhaps with a semantic URL of `/`/m/{userid)/projects`) and linked to from the Projects feed page.

I can speak more to why this is what is feeling better, but @tibetsprague is this still open for discussion?

**Comment by tibetsprague** [comment]
Yeah actually in the latest profile designs from Aaron we have a projects section that shows the projects the person is involved in. I agree this makes sense. What I heard from design science studio is an easy way for people to see their projects so the profile would probably work just as well for that? I would love to hear your opinion.

**Comment by tibetsprague** [comment]
will be solved instead by https://github.com/Hylozoic/hylo-evo/issues/631
