### ISSUE TITLE
People are getting stuck at https://www.hylo.com/signup/upload-photo

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#661]
It appears that if someone has not uploaded an avatar image they cannot use hylo, it always redirects them back to https://www.hylo.com/signup/upload-photo

We should let people use Hylo without an image

**Comment by lorenjohnson** [comment]
The workflow for sign-up is that each step of the sign-up wizard has to be passed through  which sets `Users.settings>sign_up_inprogress = true` . There is no requirement for uploading a profile photo, the user should be able to just hit `Next`, review their "Skills and Interests" tags and complete the sign-up. It's understandably confusing if someone was never returned to the sign-up wizard after exiting early on initial sign-up, and we could probably write a migration to mark users with certain kinds of activity to `sign_up_inprogress = false` to avoid this confusion. 

I am concerned if someone is saying they stuck or as the report of seeing a "blank screen" that there is something I'm not seeing, but am hoping for a user id we can test against.

**Comment by tibetsprague** [comment]
got an example
user: lili.ingmann@gmx.de
pw: ask tibet

**Comment by lorenjohnson** [comment]
Ok, the issue was with the sign-up routes coming after the sign-up redirect, so I should actually have been able to easily reproduce this 👎  Sorry. Fixed now in the linked PR. Marked you for review--let's get this out there 🎆
