### ISSUE TITLE
Stop upvoting from moving a post back to top of the stream

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#665]

**Comment by lorenjohnson** [comment]
@tibetsprague  Ok, so it turns-out my theory that upvotes update update_at on posts is false. They do not. The only thing that I see beyond post.title and post.description which refreshes updated_at is when a new comment is added. This also reflects in my testing in the UI with the for the "Latest" sort order. 

Also worth noting is that the "Most Popular" sort order sorts posts according to posts.num_votes. 

So the specific task is invalid, but the more general UX concern with confusion around post sorting needs further research.
