### ISSUE TITLE
Change post title placeholder - "What's on your mind is not clear"

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#680]
People dont know they need to fill it out. Also need to show an error message if it is not filled out.

Also we shouldnt use the same text in the comment box too.

**Comment by wushenshen** [comment]
@tibetsprague there's feedback from an Intercom user expressing it's not clear how to create a post (or project) - so that would be able the "Hi ____, what's on your mind?" text input on a community's home page. It's slightly different than this but feels related.

**Comment by geofffitch** [comment]
The additional issue is the reply box has the same text. So when a post is open there are two windows on the screen that both say "what's on your mind". Often you see the stream on the left at the post you are viewing and the post box above and the post on the right with the reply box below. Not obvious for less experienced users. Something more specific like "create a post" and "reply to this post" would be clearer.
