### ISSUE TITLE
Editing fields on Review screen of sign-up doesn't work

### ISSUE THREAD

**Issue by lorenjohnson** [Hylozoic/hylo-evo#685]
Fails silently in production (nothing happens when clicking on edit button), fails with error in development (see attached image)
![image](https://user-images.githubusercontent.com/6294/97559226-3c6a3100-1981-11eb-8a49-9cf82f114644.png)

**Comment by tibetsprague** [comment]
i wonder if this is similar/related to this bug that i fixed in the community templates branch: https://github.com/Hylozoic/hylo-evo/issues/579

**Comment by lorenjohnson** [comment]
Perhaps. I looked at the issue briefly when I noticed it and it seemed not
too difficult to track down. Likely something ref's related and has
probably been broken for a long time (likely since upgrade to React 16)
