### ISSUE TITLE
Threaded comments

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#736]
Add one level deep of nested replying to comments. If you try to reply to a reply then it just creates a new topic at the bottom of that thread of replies with the poster of the comment @tagged (like how Facebook does it when you try to reply more than two levels deep).

Designs: https://www.figma.com/file/0TFLlBLYwq8B7Nb35otrI9/Threaded-comments-%26-Reactions

Ignore the reactions part of those designs for now

One question to still discuss, we probably dont want threaded comments in direct message threads, but maybe we do? Those threads are using the same code/interface as post comments so adding threads in one place would add it in both in theory. lets discuss

Related to https://github.com/Hylozoic/hylo-node/issues/580

**Comment by lorenjohnson** [comment]
> Add one level deep of nested replying to comments. If you try to reply to a reply then it just creates a new topic at the bottom of that thread of replies with the poster of the comment @tagged (like how Facebook does it when you try to reply more than two levels deep).
> 
> 
> 
> Designs: https://www.figma.com/file/0TFLlBLYwq8B7Nb35otrI9/Threaded-comments-%26-Reactions
> 
> 
> 
> Ignore the reactions part of those designs for now
> 
> 
> 
> One question to still discuss, we probably dont want threaded comments in direct message threads, but maybe we do? Those threads are using the same code/interface as post comments so adding threads in one place would add it in both in theory. lets discuss
> 
> 
> 
> Related to https://github.com/Hylozoic/hylo-node/issues/580

My vote is that for the scope of this ticket we nail this feature for Post comments, and consider or address the possibilities for messages independently on a different ticket and timeline.

**Comment by pospi** [comment]
Made some good progress today, see https://github.com/Hylozoic/hylo-evo/compare/736-threaded-comments for WIP.

**Things still to do:**

- [ ] finalise the appearance of the sub-comment control 
- [ ] focus sub-comment input immediately when clicking the "reply" button
- [ ] wire up layout correctly to insert sub-comments in the appropriate locations

The third item will depend heavily on the optimal backend implementation, see Hylozoic/hylo-node#580 for more on this.

**Comment by pospi** [comment]
What exists now is something you could call an MVP. It would be good to get @brodeur's feedback to see if the user experience feels right. Some decisions made around how interface elements behave that are difficult to communicate textually, but I'll try.

- Clicking any reply button/icon in a sub-thread always opens the reply box at the bottom of the thread, 1 level deep.
- Comments added as sub-comments are only ever created as immediate children of the toplevel comment.
- Have a think about whether closing the reply box is a valid UI action once opened, or whether we should just let it sit there (which IIRC is how FB does it).

There's a note to make about this update that will be relevant in upgrading to a fully fractal commenting architecture in future. The code in the comment connector files might need some refactoring as it's where the bulk of the comment reply UI binding logic resides. This makes it a bit awkward to rebind creation parameters for sub-comments across the component tree, when really each `Comment` component could just take such parameters as props and share callbacks between instances.

Are there any plans to make comments deep-linkable? Just curious as it would impact some loading behaviours.

Still to do:

- [ ] Add "load previous comments" button and progressively display sub-comments
- [ ] Wire up fetching of older sub-comment replies from server

**Comment by cpolitano** [comment]
From aaron and tibet: looks great so far! we like the decisions you've made. We would like comments to be deep linkable eventually but they dont need to be now

**Comment by pospi** [comment]
Ready for review, all the rough edges should be pretty good now and the realtime features are implemented too.

There's some perhaps strange code that handles the focus on the reply field after clicked- the reason it's in the `Comments` container and not in each `Comment` is that initially I was doing some additional measuring of DOM elements at that level of the component tree to prevent overlapping with the toplevel reply box. The new scrolling behaviour seems a little more capable than what I had initially so this may no longer be required, but I wanted to get some good QA of the scrolling / focusing behaviour to ensure such things aren't needed before cleaning it up.

Another possible option is to fiddle with some layout CSS so that the bottom reply box is no longer an overlay, and just sits at the bottom of the thread. I've always found the input being at the bottom of the screen a little awkward on larger monitors so would take this as an opportunity to change things if other folks think it's sensible... YMMV (;

**Comment by tibetsprague** [comment]
I agree that the reply box should just sit at the bottom of the thread! Maybe Lo’ren knows why it works the way it does

Sent by m

**Comment by lorenjohnson** [comment]
> I agree that the reply box should just sit at the bottom of the thread! Maybe Lo’ren knows why it works the way it does 

I think it was spec'd in the original MetaLabs design and likely arises from a "mobile first" principle. In short, I think if we all prefer it inline we should just do that, though IMHO best as a new ticket and separate effort.
