### ISSUE TITLE
Navigating to most Member Profiles crashes with ReduxORM Membership query error (on dev)

### ISSUE THREAD

**Issue by lorenjohnson** [Hylozoic/hylo-evo#754]
@tibetsprague I found after merging the ReduxORM branch to dev. Navigating to `/c/hylo/m/982` (or I think maybe most any member profile) results in `Error: Expected to find a single row in `Membership.get`. Found 2.. 

I looked into it a bit and didn't come-up with a ready solution. I may by the time I finish this update but I wanted to alert you to it in case you have a ready answer. This relates to `Model.extension.js#safeGet` which we previously wrapped in a `try / catch` and might have been throwing away the error, though it does look like a new version ReduxORM issue.

**Comment by tibetsprague** [comment]
Seems like a good thing i removed that try catch as it was swallowing real errors. I think this error was why the red dot counts are not being reset currently on prod...?
