### ISSUE TITLE
Add ability to resize group photo

### ISSUE THREAD

**Issue by cpolitano** [Hylozoic/hylo-evo#771]
Requested by Max @ PHA: "When I was setting up the group page, I struggled to get the logo photo to be to the right scale and noticed there wasn't any resizing function for the picture/thumbnail of a group. Flagging this not because its SUPER high priority, but because it's something that makes hylo feel not as smooth as the platforms I've become accustomed to and maybe it's an easy thing to integrate"

**Comment by tibetsprague** [comment]
after discussion it seems that current tools are probably good enough.

**Comment by tibetsprague** [comment]
we depend on filepicker features for this anyway and so can only do what they can do for now

**Comment by tibetsprague** [comment]
we already have this through filestack
