### ISSUE TITLE
Users have to answer join questions when invited to join a group

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#792]
https://www.figma.com/file/CcODuMOQv9ShB1ryHTDqfr/Onboarding-Flow?node-id=0%3A1&viewport=-123%2C-1619%2C0.34902629256248474

- [ ] When clicking on an invite link, after joining the group show pop up modal with questions to answer (as part of Group Welcome modal)
- [ ] These are optional questions for now, answers can be blank, but do get saved
- [ ] Question: if there are group agreements do we show these before or after in a long list? or separate steps of the Group Welcome modal?
- [ ] Eventually could have a setting to say whether they have to answer or not
- [ ] Purpose & Agreements come first as first page, then next to see join questions & suggested skills

**Comment by thomasgwatson** [comment]
I started looking at this but realized it hinges a bunch on the agreement work you are in the middle of, and I didn't want to cause massive merge conflicts. I'll do the mobile version for now and come back to this once you've had a shot at adding the recheck of agreements when they change
