### ISSUE TITLE
Invite expired page is broken/empty

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#833]
Probably a routing related issue

- [ ] Going to an invalid invite link goes to infinite spinner, should show an error message. There is an error here that is not being caught/handled
- [ ] Also check an invite link that was sent to someone by email and then expired

What should it show? An invite expired error page with the (Jolly/sad?) Axolotl, some work to do here

**Comment by thomasgwatson** [comment]
How do we easily replicate invalid invite links?
- Can you invite someone, and then revoke the invite? Does that invalidate the invite?
@tibetsprague @lorenjohnson ?

**Comment by tibetsprague** [comment]
Also you can just just change a letter in the link :)

**Comment by thomasgwatson** [comment]
Ahh yes excellent! Just chatted with Annie about a next ticket.

**Comment by lorenjohnson** [comment]
FYI `checkInvitation` is not returning the correct result for expired invitations on the backend (for direct invites with `invitationToken` vs the open Group Invite URL) , addressing that then will look into the flow of things once there is an expired invite both in the Auth and Non-Auth contexts.
