### ISSUE TITLE
Play embedded video and audio links in the post

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#885]
When you include a playable link in a post you should be able to see and play the video directly in the post using embedded players. 

List to support in priority order
- YouTube
- Vimeo
- soundcloud

Bonus:
- Facebook video links

First embed should be the primary banner "image" of the post. clicking on it should play the video
Other videos could just stay links for now, or be smaller embeds at the bottom of the post body as a bonus

**Comment by thomasgwatson** [comment]
https://www.npmjs.com/package/@draft-js-plugins/video

**Comment by brodeur** [comment]
@tibetsprague What design is needed for this?

**Comment by tibetsprague** [comment]
im not totally sure, does the design described above make sense? certainly a dev could give it a shot and see what you think of it. one question is whether to try and include multiple video embeds or just the first one?
