### ISSUE TITLE
Text Formatting in Posts

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#886]
Bold, italic, underline, headers, lists...

use markdown?

DraftJS has all this built in, we could save draftjs format in the database and then convert when we display

**Comment by lorenjohnson** [comment]
As much as I do love Markdown, I don't see a case for storing to Markdown and believe it would add problems vs solve any. 

The best bet here is to move to storing the raw DraftJS `contentState` and converting to HTML on display. Markdown transcription to the DB would add another layer introducing possible and unnecessary challenges in translation to/from editor and display. Currently we store HTML which is where generally our issues come from in terms of consistency of format. With a raw DraftJS `contentState` in the database it will be easier to shorten the path and normalize text display between Web and Mobile by having the only transformations that happen to the display text by policy happen as a function in `hylo-utils`. 

In terms of adding formatting features and the UX of that there is a default and decent DraftJS toolbar usable for that and a few plugins available for inline Medium editor style block formatting. The first step would be catching-up own little DraftJS ecosystem to the latest versions to be able to get to the best of all of that. (<-- I've auditions and scoped that work already and it doesn't look too bad.)

**Comment by lorenjohnson** [comment]
Here is a list of what I think we should do with this, which once refined we could make the task list or another predatory ticket:

- [ ] Upgrade all DraftJS stuff to latest and get it working
- [ ] Change front-end (both Web and Mobile) and backend code to reflect storing post.details format to store as DraftJS raw contentState
- [ ] Write and stage post.details format conversion migration on backend
- [ ] Address editing vs display consistency issues on both and between Web and Mobile editors and presentation (#640, #1029, etc)
- [ ] Add default and/or plugin formatting on Web to Post editor including addressing how this will be handled (or not) in the Mobile Post Editor 
- [ ] Preview / design review this first pass on staging

**Comment by tibetsprague** [comment]
@lorenjohnson can we close this?
