### ISSUE TITLE
Add `farm-collaborate` widget

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo-evo#947]
A widget that shows what forms of collaboration farmers are open to

**Comment by thomasgwatson** [comment]
https://www.figma.com/file/ds9HkBxld0mBFfv1O3rihz/Group-Explorer?node-id=0%3A1

@brodeur do we have assets for the little symbols on the left? We need a symbol for [
              "research",
              "events",
              "volunteering",
              "mentorship",
              "cooperative",
              "buy"
            ]

![image](https://user-images.githubusercontent.com/5193218/155234023-605d44f1-62df-42b1-ab62-a9cd2a011d67.png)

**Comment by tibetsprague** [comment]
@brodeur when someone clicks on one of these does it just open a message to all of the moderators of the group?

**Comment by tibetsprague** [comment]
slightly unclear where exactly this is displayed. is this only displayed on the public "about" page? or also in the about sidebar when you are a member of the group

**Comment by thomasgwatson** [comment]
On the public page but only if the user is a "farmer"

**Comment by tibetsprague** [comment]
lets show this for all people, not just "farmers"

**Comment by thomasgwatson** [comment]
This is pretty much good to go, and should be fairly straightforward for someone else to knock out (once we have the assets)

**Comment by brodeur** [comment]
[icons.zip](https://github.com/Hylozoic/hylo-evo/files/8181924/icons.zip)
