### ISSUE TITLE
Hylo loading slowly (and sometimes failing to load) on Firefox

### ISSUE THREAD

**Issue by gcassel** [Hylozoic/hylo-evo#950]
Hi, I'm noting that every time I've tried to use Hylo on Firefox on a Windows 10 PC this week,  it has either taken several minutes to even partially load (to the point that basic UI elements showed up) or, more often, has not loaded at all in 5 minutes or more.  This has happened probably at least 1-2 times per day for five days in a row.   

I hadn't used Hylo for months previously, so I have no idea when the problem started.  Hylo works fine on Google Chrome using the same system & OS.

**Comment by gcassel** [comment]
FYI this problem is _not_ evident today while revisiting Hylo on Firefox on the same Windows 10 PC; therefore I'm tempted to think that the issue is resolved, although it deserves some repeat visits (with Firefox) to verify reliability.

**Comment by tibetsprague** [comment]
Thanks Greg, glad to hear that, we will keep testing.

**Comment by gcassel** [comment]
Note, the performance issue with Firefox is definitely not _fully_ resolved, although it seems much better.  I'd say about 25-50% of the time I load Hylo in a _new_ Firefox window/instance, it takes anywhere from 30-120 seconds to load.  (The other times it's 10 seconds or less.) I haven't noticed any problems with new Hylo tabs in the same Firefox window.  As before, no problems with Chrome.

**Comment by gcassel** [comment]
I got a more precise bug on Windows 10 + Firefox today: The Hylo window froze & then crashed with the attached error message.   
![Screenshot (541)](https://user-images.githubusercontent.com/12185989/155572385-8a44c152-2156-47d5-8025-e0f2bf684f80.png)
