### ISSUE TITLE
Expand group about page for farms (and farm users)

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo-evo#966]
When a farmer clicks on a farm group, they can see a different, more comprehensive, set of data & additional widgets. 

Currently we just see an "About us" section, a privacy section and maybe a "request to join" section

**Comment by thomasgwatson** [comment]
I am assuming that the about page will need configurable widgets, since different group types will probably require different widgets.

To introduce the concept of widgets to the "about" page for a farm group, we have several options:

1. hardcode a conditional rendering for farm groups and add a fixed bunch of widgets when its a farm group
2. introduce new widget records in the db for each 'about' widget, and add those for every group (with farm and regular groups having different sets of about widgets)
3. introduce a new `type` or `page` column to the `group_widgets`, add the appropriate data to existing `group_widgets` records and add the appropriate additional `group_widgets` for farms.

Option 1 is the quickest and occurs the most technical debt.
Option 2 requires no changes to the db schema but would get out of hand if we started adding more and more contexts where widgets are used in the app
Option 3 requires some database updates and would probably be the cleanest if we add another widget set.

So, how likely are we to add other areas of the application that have configurable widgets?

**Comment by tibetsprague** [comment]
im a little confused, wouldn't we need to do #2 and #3 together? we will need the new widgets, and need to know where to display them in the group. I generally like the idea of making our widget code more flexible so we can start to use widgets in more places and eventually have custom views with custom widgets on them!

**Comment by thomasgwatson** [comment]
Both 2 and 3 options will require adding completely novel widgets. The main difference is in how we handle existing widgets (one already in the explore/home page) that will be placed in a new context.

Take a group that needs a `active_members` widget on the `home` and their `about` pages. The existing home context is covered by a `group_widgets` record related to a `widgets` record (of `active_member`).

Option 2 would cover the new context of the `about` page by creating a whole new `widgets` record, say `active_member_about` and then also creating a record in `group_widgets` related to `active_member_about`. The front-end would know that both `active_member` and `active_member_about` map to the same widget but in different places.

Option 3 would instead skip creating a new `widgets` record. Instead, it would detail the context of the widget in the new column on `group_widgets`, in a new record specific to that group. So the group would have two `group_widgets` records related to the same `active_members` widget, differentiating them because they have different values in their `page` column. And the front-end would then know where to put the different widgets.

I'm not sure how much we rely on the `order` column in `group_widgets` to be correct but option two would make that a bit weird....

Does that explanation make it clearer what the distinction between the two options is?

**Comment by tibetsprague** [comment]
Yes thanks! And I definitely like option 3 better. Again that will make it much easier to have custom views in the future with different sets of widgets. I wonder if we might want to rename groups_widgets to be views_widgets or page_widgets… For now fine to leave as groups_widgets.

**Comment by tibetsprague** [comment]
I’m not actually sure that the components are the names we want to align around. We call the landing page Explore right, so maybe we should use that? Would be good to align the public facing names with the component names with the names in the database. Shall we do that? GroupDetail makes sense to me though.

**Comment by thomasgwatson** [comment]
> about this farm (mission, etc)
> opportunities to collaborate
> farm details (comparison)
> Requests & offers
> projects
> events
> Farm (farm landscape) map
> Farm managers
> Privacy settings

Adding these widgets to an existing group, for testing purposes

```
INSERT INTO group_widgets(group_id, widget_id, "order", created_at, context)
VALUES 
(<GroupId>, 1, 1, current_timestamp, 'group_detail'),
(<GroupId>, 15, 2, current_timestamp, 'group_detail'),
(<GroupId>, 14, 3, current_timestamp, 'group_detail'),
(<GroupId>, 4, 4, current_timestamp, 'group_detail'),
(<GroupId>, 8, 5, current_timestamp, 'group_detail'),
(<GroupId>, 7, 6, current_timestamp, 'group_detail'),
(<GroupId>, 16, 7, current_timestamp, 'group_detail'),
(<GroupId>, 17, 8, current_timestamp, 'group_detail'),
(<GroupId>, 18, 9, current_timestamp, 'group_detail');
```

**Comment by thomasgwatson** [comment]
Ok, looks like the `GroupDetail` component is doing double time: used in two places. One is internally facing and one externally facing.

How it is used when someone is a part of a group:
![image](https://user-images.githubusercontent.com/5193218/144524247-ba5f4aac-b003-413c-a0f3-c079eff576f9.png)

And what it looks like when you are external to a group and looking at its page:
![image](https://user-images.githubusercontent.com/5193218/144524603-7f6b0c8d-3e24-4962-89e4-bfcc04691f9f.png)

We want all these extra widgets to be available for the second instance (external user of a group) but I think it would rapidly overload and jankify the first usecase of the `GroupDetail`. So I think the better strategy is to create a whole new component (maybe we could name this one `About`) and route to that in the appropriate circumstances.
@tibetsprague Does that make sense?

**Comment by tibetsprague** [comment]
Yes I think that makes sense. We will just want to re-use components on the pages as much as we can
