### ISSUE TITLE
Group Explorer View ( /groups view for public context)

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo-evo#967]
Exploring what other groups there are out in Hylo, via the context of a group you are already in. This page will appear as the Groups view in the Public Groups and Posts context.

https://www.figma.com/file/ds9HkBxld0mBFfv1O3rihz/Group-Explorer?node-id=0%3A1

Work is prioritized so that we can pull up farm group connections, however, some of this will be applicable to any group

- [x] Search bar to allow users to type in keywords to find different groups
- [x] Query filters to allow users to filter groups by distance, group size, keyword match
- [x] ~~group-type filter, which allows the user to filter some categories of groups~~ (To be cut out into a separate ticket)

**Comment by thomasgwatson** [comment]
Implementation notes:
- Similar top title structure to the `Stream`
- Could re-use some widgets, but for the public view it will be a hard-coded set (since it will be common to all users)
- Different widget sets based on whether a user is a farmer or not. Might need some standard around widget visibility based on role

**Comment by thomasgwatson** [comment]
Aaron design notes:
**On second glance I think all groups can be much simpler:
- Groups near you (if user has a location set, groups ordered by distance, closets first
- All groups (all groups, showing groups that have topics matched to user first, with a keyword filter. Sort by: Distance, name, group size)**

**Comment by thomasgwatson** [comment]
![image](https://user-images.githubusercontent.com/5193218/151236883-6687dcfb-9a7f-48dd-aca9-bd7f8e21aea3.png)

**Comment by thomasgwatson** [comment]
![group-explorer-hero](https://user-images.githubusercontent.com/5193218/151236941-03041f6f-dbe4-4865-8fab-79f9b7582780.svg)

**Comment by thomasgwatson** [comment]
Blocking out structure
![image](https://user-images.githubusercontent.com/5193218/151595231-4696b1df-fe75-437c-9455-c510f26cd057.png)

**Comment by thomasgwatson** [comment]
![group-item-topics-description](https://user-images.githubusercontent.com/5193218/151618744-67e01a5c-68dd-4d4c-87fb-ff461164a631.png)

**Comment by thomasgwatson** [comment]
Styling updating

![image](https://user-images.githubusercontent.com/5193218/152056870-69418db7-66ba-4a9e-91a1-b76533620454.png)

**Comment by brodeur** [comment]
OK cleaned up what I could with the time I had. Two remaining tasks are: 

1) Don't render either description or tags if they don't exist -- skip the component entirely.
2) Simplify sort: "Sort: Name"
3) See if it's possible to put search input and sort side by side
