### ISSUE TITLE
Add about video for groups

### ISSUE THREAD

**Issue by tibetsprague** [Hylozoic/hylo-evo#989]
Display embedded about video at the top of the group details page/pane at the top of the About section.

**Comment by tibetsprague** [comment]
@lorenjohnson  finally got to talk through video stuff with Aaron and Clare more. So the important piece here is an “about” video that is more external facing, which appears on the about/details page/pane for a group at the top of the About section. A video in the welcome section of the explore page is cool, but not as high priority as that would probably be a different video, a welcome video. So lets set this about_video field in the group settings, and show it there as the MVP of this work.

**Comment by lorenjohnson** [comment]
Ah! All good to have clear. Will do just that.

**Comment by lorenjohnson** [comment]
So, the video will appear in at least these three contexts above the existing Group Description blurb:

https://www.hylo.com/groups/2484connect
https://www.hylo.com/public/groups/group/2484connect
https://www.hylo.com/public/map/group/2484connect
